name: Branch Name Check

on:
  create:
    branches:
      - '**'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        shell: pwsh
        env:
          BRANCH_NAME: ${{ github.ref }}
        run: |
          # Extract branch name from the reference
          if ($env:BRANCH_NAME -like 'refs/heads/*') 
          {
            $BRANCH_NAME = $env:BRANCH_NAME -replace 'refs/heads/', ''
            Write-Output "Checking branch name $BRANCH_NAME"

            if ($BRANCH_NAME -notmatch '^(feature|release|bugfix|hotfix|fix)/') 
            {
              Write-Output "Branch $BRANCH_NAME does not follow the required naming convention!"
              Write-Output "Branch name must start with feature/, release/, bugfix/, hotfix/ or fix/"
              Write-Output "Fix the branch name before creating a PR to avoid rejection"
              exit 1
            }
            else
            {
              Write-Output "Branch $BRANCH_NAME is a valid branch name"
              exit 0
            }
          } 
          else 
          {
            Write-Output "Skipping check since this is not a branch (likely a tag or other ref)."
          }
